name: rdkit
channels:
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2024.2.2
  - comm=0.2.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.28.0
  - ipython=8.12.2
  - java-jdk=7.0.91
  - jedi=0.18.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.13
  - packaging=23.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.8.18
  - python-dateutil=2.8.2
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - typing_extensions=4.9.0
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - cachedmethods==0.1.4
      - cgrtools==4.0.41
      - cimtools==4.0.8
      - joblib==1.3.2
      - lxml==5.1.0
      - numpy==1.24.4
      - pandas==2.0.3
      - pillow==10.2.0
      - pyjnius==1.6.1
      - pyparsing==3.1.2
      - pytz==2024.1
      - rdkit==2023.9.5
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - threadpoolctl==3.3.0
      - tzdata==2024.1
prefix: /home/47b38227-ee56-490a-ae8b-a925a4f4b307/.conda/envs/rdkit
